### PR TITLE
Update python libraries

### PR DESCRIPTION
**Pull request by soline-b**
* Update versions in requirements of python libraries
* Retrieve flask-login by cloning main branch of the Git

### CODE REVIEW

**Review by abergeron — CHANGES_REQUESTED** [review]
Using pip freeze is not a bad idea, but there should be a source file with only our direct dependencies, to use when we update the pip freeze since otherwise it will be a major pain to update.

**Comment by soline-b** [comment]
> Using pip freeze is not a bad idea, but there should be a source file with only our direct dependencies, to use when we update the pip freeze since otherwise it will be a major pain to update.

That's a good point! Thank you! It should be fixed in commit b58b1b080e3bfe0f5b16453435a3b11e45c69cca

**Review by abergeron — APPROVED** [review]
I meant to have files on the side (like `requirements_orig.txt`) with only our requirements and leave the pip freeze requirements in `requirements.txt`.  But this is fine too.

I'll leave you to merge it if you want to do what I said or leave it as-is.

**Comment by soline-b** [comment]
Sorry for the misunderstanding, and thanks for your clarification

**Pull request merged**
